# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_auto_20171102_2311'),
    ]

    operations = [
    ]
